name: AI-Kulup Deploy to Nginx Container

on:
  push:
    branches:
      - main  # main branch'ine her push yapıldığında çalışacak

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.PAT_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  
    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository }}:latest .
  
    - name: Push Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ github.repository }}:latest


    - name: SSH into server and pull Podman image
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_IP }}:${{ secrets.SSH_PORT }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          podman pull ghcr.io/${{ github.repository }}:latest
          podman stop ai-kulup || true
          podman rm ai-kulup || true
          podman run -d --name ai-kulup -p 5010:80 ghcr.io/${{ github.repository }}:latest
