name: AI-Kulup Deploy to Nginx Container

on:
  push:
    branches:
      - main  # main branch'ine her push yapıldığında çalışacak

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman

    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.PAT_TOKEN }} | podman login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Podman image
      run: podman build -t ghcr.io/${{ github.repository }}:latest .

    - name: Push Podman image to GitHub Container Registry
      run: |
        podman push ghcr.io/${{ github.repository }}:latest

    - name: SSH into server and pull Podman image
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          podman pull ghcr.io/${{ github.repository }}:latest
          podman stop your-container-name || true
          podman rm your-container-name || true
          podman run -d --name your-container-name -p 80:80 ghcr.io/${{ github.repository }}:latest
